# Generated by Django 3.1.2 on 2020-10-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySaleResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UTM', models.CharField(max_length=400)),
                ('items_sold', models.IntegerField()),
            ],
        ),
    ]
