# Generated by Django 3.1.2 on 2020-10-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysaleresults',
            name='page_link',
            field=models.CharField(default='/home', max_length=400),
            preserve_default=False,
        ),
    ]
