# Generated by Django 3.1.2 on 2020-10-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dailysaleresults_page_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysaleresults',
            name='day',
            field=models.DateField(default='2020-03-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysaleresults',
            name='orders',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysaleresults',
            name='refuses',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
