# Generated by Django 3.1.2 on 2020-10-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201021_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRatioToUAH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('ratio', models.FloatField()),
            ],
        ),
    ]
