# Generated by Django 3.1.2 on 2020-10-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_currencyratiotouah'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyratiotouah',
            name='date',
            field=models.DateField(default='2020-02-02'),
            preserve_default=False,
        ),
    ]
