# Generated by Django 3.1.2 on 2020-10-23 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_currencyratiotouah_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysaleresults',
            name='currency_ratio_to_UAH',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.currencyratiotouah'),
        ),
    ]
