# Generated by Django 3.1.2 on 2020-10-23 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_dailysaleresults_currency_ratio_to_uah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysaleresults',
            name='currency_ratio_to_UAH',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.currencyratiotouah'),
        ),
    ]
