# Generated by Django 3.1.2 on 2020-10-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20201023_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysaleresults',
            old_name='day',
            new_name='date',
        ),
        migrations.AddField(
            model_name='dailysaleresults',
            name='average_purchase_value_UAH',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysaleresults',
            name='in_cant_reach_status',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysaleresults',
            name='in_new_status',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysaleresults',
            name='in_not_ordered_status',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysaleresults',
            name='in_refused_status',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysaleresults',
            name='requests',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysaleresults',
            name='revenue',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
