# Generated by Django 3.1.2 on 2020-10-25 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20201025_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySaleResultsByUTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UTM', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('requests', models.IntegerField()),
                ('orders', models.IntegerField()),
                ('in_new_status', models.IntegerField()),
                ('in_cant_reach_status', models.IntegerField()),
                ('in_not_ordered_status', models.IntegerField()),
                ('in_refused_status', models.IntegerField()),
                ('ratio_approve', models.FloatField()),
                ('ratio_new', models.FloatField()),
                ('ration_cant_reach', models.FloatField()),
                ('ration_not_ordered', models.FloatField()),
                ('ratio_refused', models.FloatField()),
                ('revenue', models.FloatField()),
                ('average_purchase_value_UAH', models.FloatField()),
                ('currency_ratio_to_UAH', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.currencyratiotouah')),
            ],
        ),
        migrations.DeleteModel(
            name='DailySaleResults',
        ),
    ]
